language: android
android:
  components:
    - build-tools-21.0.1
    - android-21

notifications:
  email: false

before_install:

  # for gradle output style
  - export TERM=dumb

script: gradle build connectedCheck